/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PriceRouteImport } from './routes/price'
import { Route as OKompaniiRouteImport } from './routes/o-kompanii'
import { Route as KartaSaytaRouteImport } from './routes/karta-sayta'
import { Route as GarantiiRouteImport } from './routes/garantii'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as UslugiSlugRouteImport } from './routes/uslugi.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as RaionSlugRouteImport } from './routes/raion.$slug'
import { Route as GorodSlugRouteImport } from './routes/gorod.$slug'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as CategoryDezinfekciyaNovosibirskRouteImport } from './routes/category.dezinfekciya-novosibirsk'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceRoute = PriceRouteImport.update({
  id: '/price',
  path: '/price',
  getParentRoute: () => rootRouteImport,
} as any)
const OKompaniiRoute = OKompaniiRouteImport.update({
  id: '/o-kompanii',
  path: '/o-kompanii',
  getParentRoute: () => rootRouteImport,
} as any)
const KartaSaytaRoute = KartaSaytaRouteImport.update({
  id: '/karta-sayta',
  path: '/karta-sayta',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantiiRoute = GarantiiRouteImport.update({
  id: '/garantii',
  path: '/garantii',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiSlugRoute = UslugiSlugRouteImport.update({
  id: '/uslugi/$slug',
  path: '/uslugi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RaionSlugRoute = RaionSlugRouteImport.update({
  id: '/raion/$slug',
  path: '/raion/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GorodSlugRoute = GorodSlugRouteImport.update({
  id: '/gorod/$slug',
  path: '/gorod/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryDezinfekciyaNovosibirskRoute =
  CategoryDezinfekciyaNovosibirskRouteImport.update({
    id: '/category/dezinfekciya-novosibirsk',
    path: '/category/dezinfekciya-novosibirsk',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/faq': typeof FaqRoute
  '/garantii': typeof GarantiiRoute
  '/karta-sayta': typeof KartaSaytaRoute
  '/o-kompanii': typeof OKompaniiRoute
  '/price': typeof PriceRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/dezinfekciya-novosibirsk': typeof CategoryDezinfekciyaNovosibirskRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/gorod/$slug': typeof GorodSlugRoute
  '/raion/$slug': typeof RaionSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/faq': typeof FaqRoute
  '/garantii': typeof GarantiiRoute
  '/karta-sayta': typeof KartaSaytaRoute
  '/o-kompanii': typeof OKompaniiRoute
  '/price': typeof PriceRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/dezinfekciya-novosibirsk': typeof CategoryDezinfekciyaNovosibirskRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/gorod/$slug': typeof GorodSlugRoute
  '/raion/$slug': typeof RaionSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/faq': typeof FaqRoute
  '/garantii': typeof GarantiiRoute
  '/karta-sayta': typeof KartaSaytaRoute
  '/o-kompanii': typeof OKompaniiRoute
  '/price': typeof PriceRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/dezinfekciya-novosibirsk': typeof CategoryDezinfekciyaNovosibirskRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/gorod/$slug': typeof GorodSlugRoute
  '/raion/$slug': typeof RaionSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/faq'
    | '/garantii'
    | '/karta-sayta'
    | '/o-kompanii'
    | '/price'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/category/dezinfekciya-novosibirsk'
    | '/docs/$slug'
    | '/gorod/$slug'
    | '/raion/$slug'
    | '/services/$slug'
    | '/uslugi/$slug'
    | '/blog/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/faq'
    | '/garantii'
    | '/karta-sayta'
    | '/o-kompanii'
    | '/price'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/category/dezinfekciya-novosibirsk'
    | '/docs/$slug'
    | '/gorod/$slug'
    | '/raion/$slug'
    | '/services/$slug'
    | '/uslugi/$slug'
    | '/blog'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/faq'
    | '/garantii'
    | '/karta-sayta'
    | '/o-kompanii'
    | '/price'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/category/dezinfekciya-novosibirsk'
    | '/docs/$slug'
    | '/gorod/$slug'
    | '/raion/$slug'
    | '/services/$slug'
    | '/uslugi/$slug'
    | '/blog/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRoute
  FaqRoute: typeof FaqRoute
  GarantiiRoute: typeof GarantiiRoute
  KartaSaytaRoute: typeof KartaSaytaRoute
  OKompaniiRoute: typeof OKompaniiRoute
  PriceRoute: typeof PriceRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategoryDezinfekciyaNovosibirskRoute: typeof CategoryDezinfekciyaNovosibirskRoute
  DocsSlugRoute: typeof DocsSlugRoute
  GorodSlugRoute: typeof GorodSlugRoute
  RaionSlugRoute: typeof RaionSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  UslugiSlugRoute: typeof UslugiSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price': {
      id: '/price'
      path: '/price'
      fullPath: '/price'
      preLoaderRoute: typeof PriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-kompanii': {
      id: '/o-kompanii'
      path: '/o-kompanii'
      fullPath: '/o-kompanii'
      preLoaderRoute: typeof OKompaniiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karta-sayta': {
      id: '/karta-sayta'
      path: '/karta-sayta'
      fullPath: '/karta-sayta'
      preLoaderRoute: typeof KartaSaytaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantii': {
      id: '/garantii'
      path: '/garantii'
      fullPath: '/garantii'
      preLoaderRoute: typeof GarantiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/$slug': {
      id: '/uslugi/$slug'
      path: '/uslugi/$slug'
      fullPath: '/uslugi/$slug'
      preLoaderRoute: typeof UslugiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raion/$slug': {
      id: '/raion/$slug'
      path: '/raion/$slug'
      fullPath: '/raion/$slug'
      preLoaderRoute: typeof RaionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gorod/$slug': {
      id: '/gorod/$slug'
      path: '/gorod/$slug'
      fullPath: '/gorod/$slug'
      preLoaderRoute: typeof GorodSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/dezinfekciya-novosibirsk': {
      id: '/category/dezinfekciya-novosibirsk'
      path: '/category/dezinfekciya-novosibirsk'
      fullPath: '/category/dezinfekciya-novosibirsk'
      preLoaderRoute: typeof CategoryDezinfekciyaNovosibirskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRoute,
  FaqRoute: FaqRoute,
  GarantiiRoute: GarantiiRoute,
  KartaSaytaRoute: KartaSaytaRoute,
  OKompaniiRoute: OKompaniiRoute,
  PriceRoute: PriceRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategoryDezinfekciyaNovosibirskRoute: CategoryDezinfekciyaNovosibirskRoute,
  DocsSlugRoute: DocsSlugRoute,
  GorodSlugRoute: GorodSlugRoute,
  RaionSlugRoute: RaionSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  UslugiSlugRoute: UslugiSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
